name: "Spelling"

on:
  pull_request: null
  push:
    branches:
    - "master"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  typos_check:
    name: "Typos"
    runs-on: "ubuntu-latest"
    steps:
    -
        name: "Checkout repository"
        uses: "actions/checkout@v4"
    -
        name: "Search for misspellings"
        uses: "crate-ci/typos@master"
